name: MSYS2

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CXXFLAGS: -Werror
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v6

    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        cache: true
        pacboy: >-
          cc:p
          meson:p
          ninja:p
          pkgconf:p
          ncurses:p

    - name: Meson setup
      run: meson setup builddir

    - name: Build
      run: meson compile -C builddir

    - name: Test
      run: meson test -C builddir
